import type { Metadata } from "next"

import "./globals.css"
import { sans } from "../fonts"

export const metadata: Metadata = {
  title: "Frontend Mentor | Product Preview Card Component",
  description: "Generated by create next app",
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body
        className={`${sans.className} flex min-h-screen flex-col items-center justify-center bg-primary-cream p-4`}
      >
        {children}
        <footer className="mt-6 text-sm text-neutral-dark-grayish-blue">
          Challenge by{" "}
          <a
            href="https://www.frontendmentor.io?ref=challenge"
            target="_blank"
            className="text-primary-light-cyan underline"
          >
            Frontend Mentor
          </a>
          . Coded by{" "}
          <a
            href="https://github.com/mauLovera"
            className="text-primary-light-cyan underline"
          >
            Mauricio Lovera
          </a>
          .
        </footer>
      </body>
    </html>
  )
}
