import type { Metadata } from "next"

import "./globals.css"
import { sans } from "../fonts"

export const metadata: Metadata = {
	title: "Frontend Mentor | Product Preview Card Component",
	description: "Generated by create next app",
}

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode
}>) {
	return (
		<html lang="en">
			<body className={`${sans.className}`}>{children}</body>
		</html>
	)
}
